server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa


  mail:
    host: smtp.gmail.com
    port: 587
    username: amzadbasha5066@gmail.com
    password: 
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
   

